name: ot-pre-202411-vs-build

on:
  push:
    branches: [ "otn_pre_202411" ]
  pull_request:
    branches: [ "otn_pre_202411" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: sonic-otn-server

    steps:
    - uses: actions/checkout@v3
      path: ./${{github.run_number}}_${{ github.sha }}

    - name: build
      run: |
          make init
          make configure PLATFORM=ot-vs 
          BUILD_MULTIASIC_KVM=y make target/sonic-ot-vs.img.gz
