name: ot-pre-202411-vs-build

on:
  push:
    branches: [ "otn_pre_202411" ]
  pull_request:
    branches: [ "otn_pre_202411" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: sonic-otn-server
    defaults:
      run:
        # working-directory: ./${{github.run_number}}
        working-directory: test1

    steps:
    - uses: actions/checkout@v3
      with:
        path: test

    # - name: build
    #   run: |
    #       make init
    #       make configure PLATFORM=ot-vs 
    #       BUILD_MULTIASIC_KVM=y make target/sonic-ot-vs.img.gz
