name: ot-pre-202411-vs-build

on:
  push:
    branches: [ "otn_pre_202411" ]
  pull_request:
    branches: [ "otn_pre_202411" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: sonic-otn-server

    steps:
    - uses: actions/checkout@v3
      with:
        path: 202411_${{github.run_number}}

    - name: build
      run: |
          cd 202411_${{github.run_number}}
          make init
          make configure PLATFORM=ot-vs
          make DEFAULT_PASSWORD=admin BUILD_MULTIASIC_KVM=y SONIC_USE_PDDF_FRAMEWORK=n INCLUDE_SFLOW=n INCLUDE_NAT=n INCLUDE_MACSEC=n INCLUDE_ROUTER_ADVERTISER=n INCLUDE_TEAMD=n INCLUDE_MUX=n INCLUDE_FIPS=n target/sonic-ot-vs.img.gz 

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: otn-202411-artifact
        path: |
          202411_${{github.run_number}}/sonic-installer.img
          202411_${{github.run_number}}/target/*.img.gz
