name: ot-pre-202411-vs-build

on:
  push:
    branches: [ "otn_pre_202411" ]
  pull_request:
    branches: [ "otn_pre_202411" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: sonic-otn-server

    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
          make init
          make configure PLATFORM=ot-vs 
          BUILD_MULTIASIC_KVM=y make target/sonic-ot-vs.img.gz
